export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const SET_CURR_ITEM_COMMENT = 'SET_CURR_ITEM_COMMENT';
export const SET_CURR_ITEM_AMOUNT = 'SET_CURR_ITEM_AMOUNT';
export const SET_CURR_ITEM_CATEGORY = 'SET_CURR_ITEM_CATEGORY';
export const SET_CURR_ITEM_DATE = 'SET_CURR_ITEM_DATE';
export const CLEAR_CURR_ITEM_VARS = 'CLEAR_CURR_ITEM_VARS';

export const ADD_SUCCESS = 'ADD_SUCCESS';
export const ADD_FAIL = 'ADD_FAIL';
export const ADD_START = 'ADD_START';
